<script setup>
import { ref, watch, computed } from 'vue';
import { useProjectStore } from '@/stores/project.store';
import BaseModal from '@/components/ui/BaseModal.vue';
import BaseButton from '@/components/ui/BaseButton.vue';
import BaseInput from '@/components/ui/BaseInput.vue';
import BaseSelect from '@/components/ui/BaseSelect.vue';

const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false
  },
  isOpen: {
    type: Boolean,
    default: false
  }
});

const emit = defineEmits(['update:modelValue', 'created', 'close']);

const isVisible = computed(() => props.modelValue || props.isOpen);

const projectStore = useProjectStore();

const leadOptions = [
  { value: 'Alex Morgan', label: 'Alex Morgan (Lead Architect)' },
  { value: 'Samir Khan', label: 'Samir Khan (DevOps Lead)' },
  { value: 'Elena Rostova', label: 'Elena Rostova (Mobile Lead)' },
  { value: 'Jane Doe', label: 'Jane Doe (Senior Engineer)' }
];

const statusOptions = [
  { value: 'active', label: 'Active (Sprint Active)' },
  { value: 'planning', label: 'Planning (Backlog Mode)' }
];

const form = ref({
  name: '',
  key: '',
  description: '',
  leadName: 'Alex Morgan',
  status: 'active'
});

const errors = ref({
  name: '',
  key: ''
});

const isSubmitting = ref(false);
const autoGeneratedKey = ref(true);

// Auto-generate key from project name if user hasn't manually edited key
watch(() => form.value.name, (newName) => {
  if (autoGeneratedKey.value && newName) {
    const words = newName.trim().split(/\s+/);
    let keyProposal = '';
    if (words.length === 1) {
      keyProposal = words[0].slice(0, 4).toUpperCase();
    } else {
      keyProposal = words
        .map((w) => w[0])
        .join('')
        .slice(0, 5)
        .toUpperCase();
    }
    form.value.key = keyProposal.replace(/[^A-Z0-9]/g, '');
  }
});

function handleKeyInput(val) {
  autoGeneratedKey.value = false;
  form.value.key = val.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 10);
  validateKey();
}

function validateName() {
  if (!form.value.name.trim()) {
    errors.value.name = 'Project name is required.';
    return false;
  }
  if (form.value.name.trim().length < 3) {
    errors.value.name = 'Project name must be at least 3 characters.';
    return false;
  }
  errors.value.name = '';
  return true;
}

function validateKey() {
  const key = form.value.key.trim().toUpperCase();
  if (!key) {
    errors.value.key = 'Project key is required (e.g. PILOT).';
    return false;
  }
  if (key.length < 2 || key.length > 10) {
    errors.value.key = 'Project key must be between 2 and 10 alphanumeric characters.';
    return false;
  }
  if (!/^[A-Z0-9]+$/.test(key)) {
    errors.value.key = 'Project key must contain only uppercase letters and numbers.';
    return false;
  }
  const existing = projectStore.getProjectByKey(key);
  if (existing) {
    errors.value.key = `Key "${key}" is already used by ${existing.name}.`;
    return false;
  }
  errors.value.key = '';
  return true;
}

async function handleSubmit() {
  const isNameValid = validateName();
  const isKeyValid = validateKey();

  if (!isNameValid || !isKeyValid) return;

  try {
    isSubmitting.value = true;
    const created = await projectStore.createProject({
      name: form.value.name,
      key: form.value.key,
      description: form.value.description,
      leadName: form.value.leadName,
      status: form.value.status
    });

    emit('created', created);
    handleClose();
  } catch (err) {
    errors.value.key = err.message;
  } finally {
    isSubmitting.value = false;
  }
}

function handleClose() {
  form.value = {
    name: '',
    key: '',
    description: '',
    leadName: 'Alex Morgan',
    status: 'active'
  };
  errors.value = { name: '', key: '' };
  autoGeneratedKey.value = true;
  emit('update:modelValue', false);
  emit('close');
}
</script>

<template>
  <BaseModal
    :modelValue="isVisible"
    @update:modelValue="(val) => { emit('update:modelValue', val); if (!val) emit('close'); }"
    @close="handleClose"
    size="md"
    title="Create New Project"
    description="Set up a workspace for your team, tickets, sprints, and documentation."
  >
    <form @submit.prevent="handleSubmit" class="create-project-form">
      <!-- Project Name -->
      <div class="form-group">
        <label for="proj-name" class="form-label required">Project Name</label>
        <BaseInput
          id="proj-name"
          v-model="form.name"
          placeholder="e.g. Data Pipeline Engine"
          :error="errors.name"
          @blur="validateName"
          autocomplete="off"
        />
      </div>

      <!-- Project Key -->
      <div class="form-group">
        <label for="proj-key" class="form-label required">Project Key</label>
        <BaseInput
          id="proj-key"
          :modelValue="form.key"
          @update:modelValue="handleKeyInput"
          placeholder="e.g. PIPE"
          :error="errors.key"
          @blur="validateKey"
          autocomplete="off"
        />
        <span class="field-hint text-muted">
          Used as prefix for ticket identifiers (e.g. <code>{{ form.key || 'KEY' }}-101</code>).
        </span>
      </div>

      <!-- Description -->
      <div class="form-group">
        <label for="proj-desc" class="form-label">Description (Optional)</label>
        <textarea
          id="proj-desc"
          v-model="form.description"
          rows="3"
          class="form-textarea"
          placeholder="Briefly describe the mission and deliverables of this project workspace..."
        ></textarea>
      </div>

      <div class="form-row-dual">
        <!-- Project Lead -->
        <div class="form-group">
          <label for="proj-lead" class="form-label">Project Lead</label>
          <BaseSelect
            id="proj-lead"
            v-model="form.leadName"
            :options="leadOptions"
            size="md"
          />
        </div>

        <!-- Initial Status -->
        <div class="form-group">
          <label for="proj-status" class="form-label">Initial Status</label>
          <BaseSelect
            id="proj-status"
            v-model="form.status"
            :options="statusOptions"
            size="md"
          />
        </div>
      </div>
    </form>

    <template #footer>
      <BaseButton variant="close" size="md" @click="handleClose">
        Cancel
      </BaseButton>
      <BaseButton
        variant="primary"
        size="md"
        :loading="isSubmitting"
        @click="handleSubmit"
      >
        {{ isSubmitting ? 'Creating Workspace...' : 'Create Workspace' }}
      </BaseButton>
    </template>
  </BaseModal>
</template>

<style scoped>
.create-project-form {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: var(--space-1);
}

.form-label {
  font-size: var(--text-sm);
  font-weight: var(--font-weight-medium);
  color: var(--text-primary);
}

.form-label.required::after {
  content: ' *';
  color: var(--color-danger-500);
}

.field-hint {
  font-size: var(--text-xs);
  margin-top: 2px;
}

.field-hint code {
  font-family: var(--font-mono);
  background-color: var(--bg-surface);
  padding: 1px 4px;
  border-radius: var(--radius-xs);
  border: 1px solid var(--border-default);
  color: var(--color-primary-400);
}

.form-textarea {
  width: 100%;
  background-color: var(--bg-surface);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-md);
  padding: var(--space-3);
  color: var(--text-primary);
  font-family: var(--font-sans);
  font-size: var(--text-sm);
  outline: none;
  resize: vertical;
  transition: border-color var(--transition-fast);
}

.form-textarea:focus {
  border-color: var(--border-focus);
}

.form-row-dual {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--space-4);
}

.form-select {
  height: 36px;
  background-color: var(--bg-surface);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-md);
  padding: 0 var(--space-3);
  color: var(--text-primary);
  font-family: var(--font-sans);
  font-size: var(--text-sm);
  outline: none;
  cursor: pointer;
  transition: border-color var(--transition-fast);
}

.form-select:focus {
  border-color: var(--border-focus);
}

@media (max-width: 640px) {
  .form-row-dual {
    grid-template-columns: 1fr;
  }
}
</style>
